### ISSUE TITLE
Cannot find _preprocess.sh

### ISSUE THREAD

**Issue by duskybomb** [ygorg/JCDL_2020_KPE_Eval#1]
The Readme mentions the use of `_preprocess.sh`. However, it isn't there in the repository.

**Comment by ygorg** [comment]
Hi ! The `_preprocess.sh` file you are refering to are located in [`boudinfl/ake-datasets`](https://github.com/boudinfl/ake-datasets) for example in [KPCrowd](https://github.com/boudinfl/ake-datasets/tree/master/datasets/500N-KPCrowd/src)

**Comment by duskybomb** [comment]
Thank you!
